name: hal
channels:
    - conda-forge
    - defaults
dependencies:
    - pip==20.0.2
    - python==3.7.3
    - tensorflow=1.15.0
    - numpy=1.20
    - tensorboard
    - mpi4py
    - pip:
        - gym==0.17.3
        - tensorflow==1.15.0
        - opencv-python==4.0.0.21
        - scikit-image==0.14.2
        - tqdm==4.31.1
        - pandas==0.24.1
        - seaborn==0.9.0
        - roboschool==1.0.49
        - torchmeta
        - torch==1.7.0+cu92
        - torchvision==0.8.1+cu92
        - torchaudio==0.7.0
        - -f https://download.pytorch.org/whl/torch_stable.html
        - glfw
        - Cython
        - imageio
        - lockfile
        - jupyterlab
        - imageio-ffmpeg
        - sklearn
        - git+git://github.com/openai/baselines.git@8e56dd#egg=baselines
        - wandb
        - sparse
        - statsmodels
